### ISSUE TITLE
USER STORY: Register users as Content Creators

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/dys#40]
As **Administrator**, I can **Give privileges to users to became Content Creators**, so that **This content creators can handle DIY projects**
---

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am an administrator
	**When** a user is designed as Content Creator
	**Then** I can assign this user to the Content Creator user group
- Acceptance Criteria 2
	**Given** that I am an administrator
	**When** a user is no longer designed as Content Creator
	**Then** I can revoke their Content Creator user privileges
- Acceptance Criteria 3
	**Given** that I am a Content Creator
	**When** I want to create/modify/delete a DIY Project
	**Then** I have sufficient privileges to perform those tasks

## Tasks
- [x] Task 1 Create ` Content Creators` users group
- [x] Task 2 Assign sufficient privileges to the ` Content Creators` users group
- [x] Task 3 Assign designated users to the ` Content Creators` users group

## Story Points:
1+1+1
## Epic:  
#37
## Iteration:
[DIY Site Backlog](https://github.com/Juanma1313/dys/milestone/1)
