### ISSUE TITLE
USER STORY: View the list of Comments/Replies for a selected DIY project

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/dys#43]
As **user**, I can **view the list of Comments/Replies assigned to a particular DIY Project**,
so that **I can read what other users have to say about the project**

###### Acceptance Criteria
- Acceptance Criteria 1
**Given** that I am a user
**When** I am viewing a DIY Project details
**Then** I can view the list of all the comments and replies about the project

###### Tasks
- [x] Task 1 – Create the Comment object model
- [x] Task 2 – Create the CommentAdmin class for the admin pages 
- [x] Task 3 – Modify the ThingDetail class view to include Comments 
- [x] Task 4 – Modify the thing_detail.html template to include comments list
