### ISSUE TITLE
USER STORY: Delete your own comment for a selected DIY project

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/dys#47]
As **registered user**, I can **delete my own Comment/Reply assigned to a particular DIY Project**, so that **I can remove completely the comment information and all the associated replies**

## Acceptance Criteria
- Acceptance Criteria 1
**Given** that I am a registered user, viewing the comments section for a DIY Project
**When** I press the delete button of one of my comments (or replies)
**Then** A modal window will request deletion confirmation

- Acceptance Criteria 2
**Given** that I am requested to confirm a comment deletion
**When** I press the delete button
**Then** the comment and all associated replies are removed from the system

## Tasks
- [x] Task 1 – Create the comment_delete function view to handle Comments deletion
- [x] Task 2 – Modify the thing_detail.html template to have a modal window for comments deletion confirmation
- [x] Task 2 – Modify the thing_detail.html template to handle comments deletion
